sourceSinkAppName: sourcesinkapp
dbName: postgresserver
sourceSinkImageName: angular2guy/sourcesink
sourceSinkImageVersion: latest
dbImageName: postgres
dbImageVersion: 16
volumeClaimName: postgres-pv-claim
persistentVolumeName: task-pv-volume
sourceSinkServiceName: sourcesinkservice
dbServiceName: postgresservice

kafkaName: kafkaapp
kafkaImageName: bitnami/kafka
kafkaImageVersion: latest
kafkaServiceName: kafkaservice

secret:
  nameSourceSink: source-sink-env-secret
  nameDb: db-env-secret
  nameKafka: kafka-env-secret

envKafka:
  normal: 
    KAFKA_CFG_NODE_ID: 0
    KAFKA_CFG_PROCESS_ROLES: controller,broker
    KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafkaservice:9093
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_SERVER_NAME: kafkaservice
    KAFKA_SERVICE_NAME: kafkaserver

envDb:
  normal: 
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/datastream"
    POSTGRES_DB: datastream
    POSTGRES_SERVER: postgresservice
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    
envSourceSink:
  normal: 
    JPA_SHOW_SQL: true
    SHUTDOWN_PHASE: 10s
    SPRING_PROFILES_ACTIVE: "prod"
    KAFKA_SERVICE_NAME: kafkaService
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/datastream"

envSoapToDb:
  normal:
    JPA_SHOW_SQL: true
    SHUTDOWN_PHASE: 10s
    SPRING_PROFILES_ACTIVE: "prod"
    KAFKA_SERVICE_NAME: kafkaService
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/datastream"

envEventToFile:
  normal:
    JPA_SHOW_SQL: true
    SHUTDOWN_PHASE: 10s
    SPRING_PROFILES_ACTIVE: "prod"
    KAFKA_SERVICE_NAME: kafkaService
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/datastream"

envDatabaseToRest:
  normal:
    JPA_SHOW_SQL: true
    SHUTDOWN_PHASE: 10s
    SPRING_PROFILES_ACTIVE: "prod"
    KAFKA_SERVICE_NAME: kafkaService
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/datastream"